# Generated by Django 5.1.7 on 2025-03-27 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('offer', 'Offre'), ('demand', 'Demande')], default='offer', max_length=255)),
                ('section', models.CharField(choices=[('artists_groups', 'Artistes & Groupes'), ('courses_training', 'Cours & Formations'), ('calls_events', 'Appels & Événements'), ('services_equipment', 'Services & Matériel')], default='artists_groups', max_length=255)),
                ('category', models.CharField(choices=[('unpaid', 'Bénévole'), ('paid', 'Rémunéré')], default='unpaid', max_length=255)),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=5000)),
                ('instrument', models.CharField(blank=True, choices=[('voice', 'Voix / Chant'), ('choir_conductor', 'Chef de chœur'), ('piano', 'Piano'), ('organ', 'Orgue'), ('harpsichord', 'Clavecin'), ('synthesizer', 'Synthétiseur'), ('accordeon', 'Accordéon'), ('violin', 'Violon'), ('viola', 'Alto'), ('cello', 'Violoncelle'), ('double_bass', 'Contrebasse'), ('viola_da_gamba', 'Viole de gambe'), ('guitar', 'Guitare'), ('electric_guitar', 'Guitare électrique'), ('bass_guitar', 'Basse'), ('mandolin', 'Mandoline'), ('lute', 'Luth'), ('oud', 'Oud'), ('sitar', 'Sitar'), ('ukulele', 'Ukulélé'), ('flute', 'Flûte'), ('recorder', 'Flûte à bec'), ('clarinet', 'Clarinette'), ('oboe', 'Hautbois'), ('bassoon', 'Basson'), ('saxophone', 'Saxophone'), ('trumpet', 'Trompette'), ('trombone', 'Trombone'), ('french_horn', 'Cor'), ('tuba', 'Tuba'), ('drums', 'Batterie'), ('classical_percussion', 'Percussions classiques'), ('djembe', 'Djembé'), ('congas', 'Congas'), ('cajon', 'Cajón'), ('electronic_music', 'MAO / Musique assistée par ordinateur'), ('dj', 'DJ / Mix'), ('sound_design', 'Sound design'), ('ondes_martenot', 'Ondes Martenot'), ('theremin', 'Thérémine'), ('other', 'Autre')], max_length=50)),
                ('style', models.CharField(blank=True, choices=[('classical', 'Musique classique'), ('baroque', 'Musique baroque'), ('romantic', 'Musique romantique'), ('contemporary_classical', 'Musique contemporaine'), ('early_music', 'Musique ancienne'), ('electroacoustic', 'Musique électroacoustique'), ('pop', 'Pop'), ('rock', 'Rock'), ('indie', 'Indé'), ('metal', 'Metal'), ('punk', 'Punk'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('funk', 'Funk'), ('soul', 'Soul'), ('reggae', 'Reggae'), ('rap', 'Rap'), ('hiphop', 'Hip-hop'), ('rnb', 'R&B'), ('electronic', 'Musique électronique'), ('techno', 'Techno'), ('house', 'House'), ('ambient', 'Ambient'), ('lofi', 'Lo-fi'), ('world', 'Musiques du monde'), ('african', 'Musique africaine'), ('arabic', 'Musique arabe'), ('indian', 'Musique indienne'), ('asian', 'Musiques asiatiques'), ('latin', 'Musique latino-américaine'), ('flamenco', 'Flamenco'), ('celtic', 'Musique celtique'), ('balkan', 'Musiques balkaniques'), ('klezmer', 'Klezmer'), ('choral', 'Musique chorale'), ('opera', 'Opéra'), ('vocal', 'Musique vocale'), ('a_cappella', 'A cappella'), ('chanson', 'Chanson française'), ('film_music', 'Musique de film'), ('musical_theatre', 'Comédie musicale'), ('experimental', 'Expérimental'), ('improvised', 'Musique improvisée'), ('sacred', 'Musique sacrée'), ('children', 'Musique pour enfants'), ('other', 'Autre')], max_length=50)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('filled', models.BooleanField(default=False)),
                ('show_author_mail', models.BooleanField(default=False)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_website', models.URLField(blank=True, null=True)),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('moderation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='moderation.moderationresult')),
            ],
        ),
    ]
